# Generated by Django 5.2.5 on 2025-09-23 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blog_author_blog_content_blog_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='title',
            new_name='blogtitle',
        ),
    ]
