# Generated by Django 5.0.6 on 2025-09-23 18:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_rename_title_blog_blogtitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='publishedAt',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 9, 23, 18, 13, 24, 546498, tzinfo=datetime.timezone.utc)),
        ),
    ]
