name: Deploy Django to EC2
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Deploy to EC2
        env:
          SSH_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          echo "$SSH_KEY" > ec2_key.pem
          chmod 400 ec2_key.pem
          scp -i ec2_key.pem -o StrictHostKeyChecking=no deploy_script.sh ubuntu@ec2-3-111-219-92.ap-south-1.compute.amazonaws.com:DjangoMarketplace/deploy_script.sh
          ssh -i ec2_key.pem -o StrictHostKeyChecking=no ubuntu@ec2-3-111-219-92.ap-south-1.compute.amazonaws.com 'bash DjangoMarketplace/deploy_script.sh'
