name: Deploy Django to EC2
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Deploy to EC2
        env:
          SSH_KEY: ${{ secrets.SSH_PRIVATE_KEY }},
          EC2_HOST: ${{ secrets.EC2_HOST }}
        run: |
          echo "$SSH_KEY" > ec2_key.pem
          chmod 400 ec2_key.pem
          scp -i ec2_key.pem -o StrictHostKeyChecking=no deploy_script.sh ec2-user@${{ env.EC2_HOST }}:deploy_script.sh
          ssh -i ec2_key.pem -o StrictHostKeyChecking=no ec2-user@${{ env.EC2_HOST }} 'bash deploy_script.sh'
