# Generated by Django 5.2.5 on 2025-08-21 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_products_featured'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='desc',
            field=models.TextField(blank=True, null=True),
        ),
    ]
